---
- name: Populate service facts
  ansible.builtin.service_facts:

# - name: remove GUI for headless
#   import_tasks: headless.yml

- name: remove networkmanager
  import_tasks: networkmanager.yml
